"""Pydantic models for the product catalog.

Defines the deterministic source-of-truth schema shared by the agent, the
catalog API, and the website layer. Inventory facts (price, size, color,
stock) live in these models and are never generated by the LLM.
"""

from pydantic import BaseModel, Field


class Variant(BaseModel):
    """A single sellable configuration of a product.

    Represents one size/color combination with its own SKU and stock level.
    """

    sku: str
    """Stock-keeping unit, unique across the catalog."""

    size: str = Field(description="Size label such as S, M, L, or XL.")
    """Size label such as ``S``, ``M``, ``L``, or ``XL``."""

    color: str
    """Color name of this variant (e.g. ``black``, ``navy``)."""

    stock: int = Field(ge=0)
    """Units currently in stock. Zero means out of stock."""


class Product(BaseModel):
    """A catalog product with its variants.

    The product ``id`` is used as the stable identity for product page URLs
    (see ``ecomm_agent.services.urls``) and for mapping RAG retrieval results
    back to catalog entries.
    """

    id: str
    """Stable product identifier (e.g. ``TSH-001``)."""

    name: str
    """Display name of the product."""

    category: str
    """Product category (e.g. ``t-shirts``, ``shoes``, ``jackets``)."""

    description: str
    """Free-text description used for embedding and lexical search."""

    price: float = Field(ge=0)
    """Retail price in the store's currency."""

    variants: list[Variant]
    """All size/color variants, including out-of-stock ones."""

    tags: list[str]
    """Short descriptive tags (e.g. ``casual``, ``athletic``)."""
