"""Response generation with LLM providers.

Builds the system and user prompts from verified agent state and calls the
generation providers in order:

1. **Anthropic** (primary),
2. **Groq** (fallback),
3. **deterministic reply** (``state.response_text``) when both providers fail.

The prompts include only verified catalog and knowledge context; the LLM is
instructed to never invent products, prices, sizes, colors, stock, shipping
promises, or discounts. Price/stock/URL data is injected from deterministic
sources, never generated by the model.
"""

from __future__ import annotations

import re
from textwrap import dedent

import httpx

from ecomm_agent.agents.state import AgentState
from ecomm_agent.core.config import settings
from ecomm_agent.observability.tracing import get_tracer, is_content_recording_enabled
from ecomm_agent.services.inventory import filter_available_variants
from ecomm_agent.services.urls import build_product_page_url

tracer = get_tracer(__name__)


def _build_product_context(state: AgentState) -> str:
    """Render the verified product context for the LLM prompt.

    Args:
        state: Agent state with retrieved products and requested filters.

    Returns:
        A multi-line string, one line per product, with verified name,
        category, price, in-stock variants, and product page URL.
    """
    if not state.retrieved_products:
        return "No verified product matches were found."

    lines: list[str] = []
    for product in state.retrieved_products:
        variants = filter_available_variants(
            product,
            size=state.requested_size,
            color=state.requested_color,
        )
        variant_text = ", ".join(
            f"{variant['color']} {variant['size']} stock={variant['stock']}"
            for variant in variants[:5]
        )
        if not variant_text:
            variant_text = "No verified variants matched the requested size/color filters."
        product_url = build_product_page_url(product.id) or "No verified product page URL configured."
        lines.append(
            f"- {product.name} | category={product.category} | price=${product.price:.2f} | variants={variant_text} | product_url={product_url}"
        )

    return "\n".join(lines)


def _build_knowledge_context(state: AgentState) -> str:
    """Render the verified knowledge context for the LLM prompt.

    Args:
        state: Agent state with retrieved knowledge snippets.

    Returns:
        A multi-line string, one line per snippet, with source type, section,
        and content.
    """
    if not state.retrieved_knowledge:
        return "No verified policy, FAQ, or size-guide snippets were found."

    lines = []
    for snippet in state.retrieved_knowledge:
        label = snippet.section or snippet.source_type
        lines.append(
            f"- source_type={snippet.source_type} | section={label} | content={snippet.content}"
        )
    return "\n".join(lines)


def _build_user_prompt(state: AgentState) -> str:
    """Build the user message sent to the LLM providers.

    Includes the original message, the classified intent, guardrail status,
    requested filters, and the verified catalog/knowledge context plus the
    deterministic fallback reply.

    Args:
        state: Agent state for the current conversation turn.

    Returns:
        The formatted user prompt string.
    """
    return dedent(
        f"""
        Customer message:
        {state.user_message}

        Classified intent:
        {state.intent or "unknown"}

        Guardrail blocked:
        {state.guardrail_blocked}
        Guardrail reason:
        {state.guardrail_reason or "none"}

        Requested filters:
        category={state.requested_category or "none"}
        color={state.requested_color or "none"}
        size={state.requested_size or "none"}
        max_price={state.price_ceiling if state.price_ceiling is not None else "none"}

        Verified catalog context:
        {_build_product_context(state)}

        Verified knowledge-base context:
        {_build_knowledge_context(state)}

        Deterministic fallback response:
        {state.response_text or ""}
        """
    ).strip()


def _build_system_prompt() -> str:
    """Build the system prompt constraining the LLM to verified data.

    Returns:
        The system prompt string.
    """
    return dedent(
        """
        You are Alta Norma Fashion's Telegram sales assistant.
        Answer in plain text suitable for Telegram.
        Use only the verified catalog and knowledge-base context provided to you.
        Never invent products, prices, sizes, colors, stock, shipping promises, or discounts.
        If a verified product_url is provided in catalog context, you may include it in the reply.
        If no verified product is available, say so directly and suggest a broader search.
        Keep the answer concise and helpful.
        """
    ).strip()


async def _generate_response_text_anthropic(state: AgentState) -> str | None:
    """Request a reply from the Anthropic Messages API.

    Args:
        state: Agent state for the current conversation turn.

    Returns:
        The generated text, or ``None`` when the API key is unset or the
        response contains no text.

    Raises:
        httpx.HTTPError: When the Anthropic API call fails.
    """
    if not settings.anthropic_api_key:
        return None

    with tracer.start_as_current_span("llm.anthropic") as span:
        try:
            span.set_attribute("llm.provider", "anthropic")
            span.set_attribute("llm.model_name", settings.anthropic_model)
            span.set_attribute("llm.max_tokens", settings.anthropic_max_tokens)
            span.set_attribute("thread_id", state.thread_id)
            if is_content_recording_enabled():
                span.set_attribute("input.value", _build_user_prompt(state)[:4000])
        except Exception:
            pass

        payload = {
            "model": settings.anthropic_model,
            "max_tokens": settings.anthropic_max_tokens,
            "system": _build_system_prompt(),
            "messages": [
                {
                    "role": "user",
                    "content": _build_user_prompt(state),
                }
            ],
        }
        headers = {
            "x-api-key": settings.anthropic_api_key,
            "anthropic-version": settings.anthropic_api_version,
            "content-type": "application/json",
        }

        async with httpx.AsyncClient(timeout=20.0) as client:
            response = await client.post(
                f"{settings.anthropic_api_base_url.rstrip('/')}/v1/messages",
                headers=headers,
                json=payload,
            )
            response.raise_for_status()

        body = response.json()
        content_blocks = body.get("content", [])
        text_parts = [
            block.get("text", "")
            for block in content_blocks
            if block.get("type") == "text" and block.get("text")
        ]
        text = "\n".join(text_parts).strip()
        result = text or None
        try:
            if is_content_recording_enabled() and result:
                span.set_attribute("output.value", result[:4000])
            usage = body.get("usage", {})
            if usage:
                span.set_attribute("llm.token_count.prompt", usage.get("input_tokens", 0))
                span.set_attribute("llm.token_count.completion", usage.get("output_tokens", 0))
            span.set_attribute("llm.response_length", len(result or ""))
        except Exception:
            pass
        return result


async def _generate_response_text_groq(state: AgentState) -> str | None:
    """Request a reply from the Groq chat completions API.

    Args:
        state: Agent state for the current conversation turn.

    Returns:
        The generated text, or ``None`` when the API key is unset or the
        response contains no text.

    Raises:
        httpx.HTTPError: When the Groq API call fails.
    """
    if not settings.groq_api_key:
        return None

    with tracer.start_as_current_span("llm.groq") as span:
        try:
            span.set_attribute("llm.provider", "groq")
            span.set_attribute("llm.model_name", settings.groq_model)
            span.set_attribute("thread_id", state.thread_id)
            if is_content_recording_enabled():
                span.set_attribute("input.value", _build_user_prompt(state)[:4000])
        except Exception:
            pass

        payload = {
            "model": settings.groq_model,
            "max_completion_tokens": settings.groq_max_completion_tokens,
            "temperature": 0.2,
            "messages": [
                {
                    "role": "system",
                    "content": _build_system_prompt(),
                },
                {
                    "role": "user",
                    "content": _build_user_prompt(state),
                },
            ],
        }
        headers = {
            "authorization": f"Bearer {settings.groq_api_key}",
            "content-type": "application/json",
        }

        async with httpx.AsyncClient(timeout=20.0) as client:
            response = await client.post(
                f"{settings.groq_api_base_url.rstrip('/')}/chat/completions",
                headers=headers,
                json=payload,
            )
            response.raise_for_status()

        body = response.json()
        choices = body.get("choices", [])
        if not choices:
            return None

        message = choices[0].get("message", {})
        text = message.get("content", "")
        result = text.strip() or None
        try:
            if is_content_recording_enabled() and result:
                span.set_attribute("output.value", result[:4000])
            usage = body.get("usage", {})
            if usage:
                span.set_attribute("llm.token_count.prompt", usage.get("prompt_tokens", 0))
                span.set_attribute("llm.token_count.completion", usage.get("completion_tokens", 0))
            span.set_attribute("llm.response_length", len(result or ""))
        except Exception:
            pass
        return result


_HALLUCINATED_DISCOUNT_RE = re.compile(r"\b(30%|50%|discount|free shipping|guaranteed shipping)\b", re.IGNORECASE)


def _validate_llm_output(text: str, state: AgentState) -> str | None:
    """Validate LLM output deterministically; return sanitized text or None if hallucination detected.

    Checks:
    - Any URL in output must be either the verified product_url(s) or frontend_base_url; otherwise strip.
    - Fabricated price like $999 that does not match any product price should be flagged.
    - Discount/shipping promises not present in knowledge context are stripped by falling back.

    Returns sanitized text, or None to trigger deterministic fallback when hallucination is severe.
    """
    if not text:
        return None
    # If guardrail blocked, LLM should not have produced a normal answer; fall back to deterministic.
    if state.guardrail_blocked:
        lowered = text.lower()
        # If LLM tries to bypass guardrail, fallback
        if "ignore" in lowered and "instruction" in lowered:
            return None

    # Validate URLs: only allow verified product page URLs
    allowed_urls: set[str] = set()
    for product in state.retrieved_products:
        url = build_product_page_url(product.id)
        if url:
            allowed_urls.add(url)
    # Also allow frontend base catalog links
    if settings.frontend_base_url:
        allowed_urls.add(settings.frontend_base_url.rstrip("/"))

    # Extract URLs from text
    url_pattern = re.compile(r"https?://[^\s]+")
    for found in url_pattern.findall(text):
        # Normalize trailing punctuation
        cleaned = found.rstrip(").,]")
        # Allow only if cleaned URL is exactly an allowed URL or under allowed base /products/
        is_allowed = any(cleaned == au or cleaned.startswith(au + "/") for au in allowed_urls)
        # Also allow if it's a product_url pattern under frontend base
        if settings.frontend_base_url and cleaned.startswith(settings.frontend_base_url.rstrip("/") + "/products/"):
            # Verify product id exists in retrieved set
            pid = cleaned.rsplit("/", 1)[-1]
            if any(p.id == pid for p in state.retrieved_products):
                is_allowed = True
        if not is_allowed:
            # Hallucinated URL → fallback to deterministic
            return None

    # If no verified products but LLM mentions a price, it likely hallucinated inventory
    if not state.retrieved_products:
        if re.search(r"\$\s*\d+(?:\.\d+)?", text):
            # Could be mentioning price ceiling from query; allow only if query had price_ceiling
            if state.price_ceiling is None:
                return None

    return text


async def generate_response_text(state: AgentState) -> str | None:
    """Generate reply text trying providers in order.

    Tries Anthropic first, then Groq. Any provider exception is swallowed so
    a failure degrades to the next provider rather than failing the turn.

    Args:
        state: Agent state for the current conversation turn.

    Returns:
        The generated text, or ``None`` when every provider is unavailable.
    """
    with tracer.start_as_current_span("llm.generate") as span:
        try:
            span.set_attribute("thread_id", state.thread_id)
            span.set_attribute("llm.provider_order", "anthropic,groq")
        except Exception:
            pass
        try:
            anthropic_response = await _generate_response_text_anthropic(state)
        except Exception as exc:
            try:
                span.record_exception(exc)
            except Exception:
                pass
            anthropic_response = None

        if anthropic_response:
            validated = _validate_llm_output(anthropic_response, state)
            if validated is None:
                try:
                    span.set_attribute("llm.validation_failed", True)
                    span.set_attribute("llm.validation_provider", "anthropic")
                except Exception:
                    pass
                anthropic_response = None
            else:
                try:
                    span.set_attribute("llm.chosen_provider", "anthropic")
                    if is_content_recording_enabled():
                        span.set_attribute("output.value", validated[:4000])
                except Exception:
                    pass
                return validated

        try:
            groq_response = await _generate_response_text_groq(state)
        except Exception as exc:
            try:
                span.record_exception(exc)
            except Exception:
                pass
            groq_response = None

        if groq_response:
            validated = _validate_llm_output(groq_response, state)
            if validated is None:
                try:
                    span.set_attribute("llm.validation_failed", True)
                    span.set_attribute("llm.validation_provider", "groq")
                except Exception:
                    pass
                groq_response = None
            else:
                try:
                    span.set_attribute("llm.chosen_provider", "groq")
                    if is_content_recording_enabled():
                        span.set_attribute("output.value", validated[:4000])
                except Exception:
                    pass
                return validated

        try:
            span.set_attribute("llm.chosen_provider", "none")
        except Exception:
            pass
        return None
